version: "2"

services:
  nginx:
    build:
      context: ./nginx
      args:
        user_uid: "$user_uid"
        user_gid: "$user_gid"
    container_name: "${COMPOSE_PROJECT_NAME}-nginx"
    depends_on:
      - source
      - php-fpm
    volumes_from:
      - source
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend
    restart: "no"

  php-fpm:
    build:
      context: ./php-fpm/${PHPVERSION}
      args:
        user_uid: "$user_uid"
        user_gid: "$user_gid"
    container_name: "${COMPOSE_PROJECT_NAME}-fpm-${PHPVERSION}"
    expose:
      - "9000"
    volumes_from:
      - source
    links:
      - mysql
    networks:
      - backend
    restart: "no"
  mysql:
    build: ./mysql/${DATABASE}
    container_name: "${COMPOSE_PROJECT_NAME}-${DATABASE}"
    volumes_from:
      - source
    expose:
      - "3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - backend
    restart: "no"

  source:
    image: alpine
    container_name: source
    volumes:
      - ./data/logs/mysql:/var/log/mysql
      - ./data/logs/nginx:/var/log/nginx
      - ./data/mysql:/var/lib/mysql
      - ./data/php_sessions:/tmp/php_sessions
      - ./www:/var/www
    networks:
      - backend
networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.255.0/24
